name: Laravel Tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, sqlite
        coverage: none
        
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache/files
        key: composer-${{ hashFiles('composer.lock') }}
        restore-keys: composer-
        
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader --no-dev
      
    - name: Copy Environment File
      run: cp .env.example .env
      
    - name: Generate Application Key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Run Database Migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force
      
    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --parallel
      
    - name: Run Feature Tests (Bible Reading Core)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan test --filter=UserAuthenticationTest
        php artisan test --filter=ReadingLogTest
        php artisan test --filter=BibleReferenceServiceTest 